baseurl: http://johnmaguire.me/
languageCode: en-us
title: john maguire's blog
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: A programmer in Ann Arbor, MI. I like open source software, trying new ideas, and exploring old ideas.
  AuthorName: John Maguire
  GitHubUser: JohnMaguire
